<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DoktersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dokters')->delete();
        DB::table('dokters')->insert([ 
                // penyakit dalam
                [
                    'nama' => 'Dr. Agus Wijaya',
                    'alamat' => 'Jl. Sudirman No. 10, Jakarta',
                    'umur' => 50,
                    'email' => 'agus.wijaya@gmail.com',
                    'password' => 'agus123',
                    'jenis_kelamin' => 'Laki-laki',
                    'status_pernikahan' => 'Sudah',
                    'latar_belakang' => 'Atas',
                    'id_spesialis' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama' => 'Dr. Indah Permata',
                    'alamat' => 'Jl. Merak No. 22, Bandung',
                    'umur' => 35,
                    'email' => 'indah.permata@gmail.com',
                    'password' => 'indah123',
                    'jenis_kelamin' => 'Perempuan',
                    'status_pernikahan' => 'Belum',
                    'latar_belakang' => 'Menengah',
                    'id_spesialis' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama' => 'Dr. Rudi Hartono',
                    'alamat' => 'Jl. Diponegoro No. 45, Surabaya',
                    'umur' => 40,
                    'email' => 'rudi.hartono@gmail.com',
                    'password' => 'rudi123',
                    'jenis_kelamin' => 'Laki-laki',
                    'status_pernikahan' => 'Cerai',
                    'latar_belakang' => 'Menengah',
                    'id_spesialis' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama' => 'Dr. Siti Nurhaliza',
                    'alamat' => 'Jl. Ahmad Yani No. 34, Yogyakarta',
                    'umur' => 37,
                    'email' => 'siti.nurhaliza@gmail.com',
                    'password' => 'siti123',
                    'jenis_kelamin' => 'Perempuan',
                    'status_pernikahan' => 'Sudah',
                    'latar_belakang' => 'Rendah',
                    'id_spesialis' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama' => 'Dr. Bambang Supriyadi',
                    'alamat' => 'Jl. Kartini No. 12, Semarang',
                    'umur' => 45,
                    'email' => 'bambang.supriyadi@gmail.com',
                    'password' => 'bambang123',
                    'jenis_kelamin' => 'Laki-laki',
                    'status_pernikahan' => 'Belum',
                    'latar_belakang' => 'Atas',
                    'id_spesialis' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                //id 2
                [
                    'nama' => 'Dr. Farah Mahardika',
                    'alamat' => 'Jl. Merpati No. 5, Malang',
                    'umur' => 38,
                    'email' => 'farah.mahardika@gmail.com',
                    'password' => 'farah123',
                    'jenis_kelamin' => 'Perempuan',
                    'status_pernikahan' => 'Sudah',
                    'latar_belakang' => 'Atas',
                    'id_spesialis' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama' => 'Dr. Iwan Hidayat',
                    'alamat' => 'Jl. Jambu No. 22, Semarang',
                    'umur' => 42,
                    'email' => 'iwan.hidayat@gmail.com',
                    'password' => 'iwan123',
                    'jenis_kelamin' => 'Laki-laki',
                    'status_pernikahan' => 'Belum',
                    'latar_belakang' => 'Menengah',
                    'id_spesialis' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama' => 'Dr. Siska Anggraini',
                    'alamat' => 'Jl. Cendana No. 18, Denpasar',
                    'umur' => 30,
                    'email' => 'siska.anggraini@gmail.com',
                    'password' => 'siska123',
                    'jenis_kelamin' => 'Perempuan',
                    'status_pernikahan' => 'Cerai',
                    'latar_belakang' => 'Rendah',
                    'id_spesialis' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama' => 'Dr. Bambang Sutrisno',
                    'alamat' => 'Jl. Kenanga No. 12, Bogor',
                    'umur' => 45,
                    'email' => 'bambang.sutrisno@gmail.com',
                    'password' => 'bambang123',
                    'jenis_kelamin' => 'Laki-laki',
                    'status_pernikahan' => 'Sudah',
                    'latar_belakang' => 'Menengah',
                    'id_spesialis' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'nama' => 'Dr. Nurhayati Puspita',
                    'alamat' => 'Jl. Anggrek No. 9, Balikpapan',
                    'umur' => 35,
                    'email' => 'nurhayati.puspita@gmail.com',
                    'password' => 'nurhayati123',
                    'jenis_kelamin' => 'Perempuan',
                    'status_pernikahan' => 'Belum',
                    'latar_belakang' => 'Atas',
                    'id_spesialis' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],               
                // 3
                [
                    'id_spesialis' => 3,
                    'nama' => 'Dr. Andini Maharani',
                    'email' => 'andini.maharani@gmail.com',
                    'password' => 'andini123',
                    'umur' => 40,
                    'alamat' => 'Jl. Melati No. 7, Surabaya',
                    'jenis_kelamin' => 'Perempuan',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Sudah',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 3,
                    'nama' => 'Dr. Raditya Pranata',
                    'email' => 'raditya.pranata@gmail.com',
                    'password' => 'raditya123',
                    'umur' => 45,
                    'alamat' => 'Jl. Mawar No. 9, Jakarta',
                    'jenis_kelamin' => 'Laki-laki',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Belum',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 3,
                    'nama' => 'Dr. Farah Kusuma',
                    'email' => 'farah.kusuma@gmail.com',
                    'password' => 'farah123',
                    'umur' => 35,
                    'alamat' => 'Jl. Anggrek No. 5, Bandung',
                    'jenis_kelamin' => 'Perempuan',
                    'latar_belakang' => 'Rendah',
                    'status_pernikahan' => 'Cerai',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 3,
                    'nama' => 'Dr. Fadli Ramadhan',
                    'email' => 'fadli.ramadhan@gmail.com',
                    'password' => 'fadli123',
                    'umur' => 42,
                    'alamat' => 'Jl. Cemara No. 12, Yogyakarta',
                    'jenis_kelamin' => 'Laki-laki',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Sudah',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 3,
                    'nama' => 'Dr. Melati Anindya',
                    'email' => 'melati.anindya@gmail.com',
                    'password' => 'melati123',
                    'umur' => 30,
                    'alamat' => 'Jl. Sakura No. 14, Bali',
                    'jenis_kelamin' => 'Perempuan',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Belum',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                //4
                [
                    'id_spesialis' => 4,
                    'nama' => 'Dr. Rendy Kusnadi',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Sudah',
                    'alamat' => 'Jl. Pelita No. 7, Jakarta Timur',
                    'email' => 'rendy.kusnadi@gmail.com',
                    'password' => 'rendy123',
                    'umur' => 42,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 4,
                    'nama' => 'Dr. Dian Syafira',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Belum',
                    'alamat' => 'Jl. Cemara No. 3, Semarang',
                    'email' => 'dian.syafira@gmail.com',
                    'password' => 'dina123',
                    'umur' => 34,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 4,
                    'nama' => 'Dr. Bayu Ananda',
                    'latar_belakang' => 'Rendah',
                    'status_pernikahan' => 'Cerai',
                    'alamat' => 'Jl. Pahlawan No. 12, Surabaya',
                    'email' => 'bayu.ananda@gmail.com',
                    'password' => 'bayu123',
                    'umur' => 40,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                //5
                [
                    'id_spesialis' => 5,
                    'nama' => 'Dr. Rendi Kurniadi',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Sudah',
                    'alamat' => 'Jl. Pelita No. 7, Jakarta Timur',
                    'email' => 'rendi.kurniadi@gmail.com',
                    'password' => 'rendy456',
                    'umur' => 42,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 5,
                    'nama' => 'Dr. Dina Syafira',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Belum',
                    'alamat' => 'Jl. Cemara No. 3, Semarang',
                    'email' => 'dina.syafira@gmail.com',
                    'password' => 'dina123',
                    'umur' => 34,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 5,
                    'nama' => 'Dr. Bagas Saputro',
                    'latar_belakang' => 'Rendah',
                    'status_pernikahan' => 'Cerai',
                    'alamat' => 'Jl. Pahlawan No. 12, Surabaya',
                    'email' => 'bagas.saputro@gmail.com',
                    'password' => 'bagas123',
                    'umur' => 40,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 5,
                    'nama' => 'Dr. Nadia Amira',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Sudah',
                    'alamat' => 'Jl. Melati No. 9, Bandung',
                    'email' => 'nadia.amira@gmail.com',
                    'password' => 'nadia123',
                    'umur' => 36,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 5,
                    'nama' => 'Dr. Arif Santoso',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Belum',
                    'alamat' => 'Jl. Anggrek No. 15, Yogyakarta',
                    'email' => 'arif.santoso@gmail.com',
                    'password' => 'arif123',
                    'umur' => 30,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 6,
                    'nama' => 'Dr. Cahya Wirawan',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Sudah',
                    'alamat' => 'Jl. Pelangi No. 12, Jakarta Barat',
                    'email' => 'cahya.wirawan@gmail.com',
                    'password' => 'cahya123',
                    'umur' => 45,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 6,
                    'nama' => 'Dr. Ardi Setiawan',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Belum',
                    'alamat' => 'Jl. Cemara No. 19, Malang',
                    'email' => 'ardi.setiawan@gmail.com',
                    'password' => 'ardi123',
                    'umur' => 37,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 6,
                    'nama' => 'Dr. Laras Prameswari',
                    'latar_belakang' => 'Rendah',
                    'status_pernikahan' => 'Cerai',
                    'alamat' => 'Jl. Merak No. 7, Semarang',
                    'email' => 'laras.prameswari@gmail.com',
                    'password' => 'laras123',
                    'umur' => 39,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                //7
                [
                    'id_spesialis' => 7,
                    'nama' => 'Dr. Arif Budiman',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Sudah',
                    'alamat' => 'Jl. Cemara No. 14, Jakarta Pusat',
                    'email' => 'arif.budiman@gmail.com',
                    'password' => 'arif123',
                    'umur' => 50,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 7,
                    'nama' => 'Dr. Dina Aulia',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Belum',
                    'alamat' => 'Jl. Kamboja No. 23, Semarang',
                    'email' => 'dinaaulia@gmail.com',
                    'password' => 'dina123',
                    'umur' => 35,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 7,
                    'nama' => 'Dr. Rizky Hartono',
                    'latar_belakang' => 'Rendah',
                    'status_pernikahan' => 'Cerai',
                    'alamat' => 'Jl. Cempaka No. 32, Surabaya',
                    'email' => 'rizky.hartono@gmail.com',
                    'password' => 'rizky123',
                    'umur' => 42,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                //8
                [
                    'id_spesialis' => 8,
                    'nama' => 'Dr. Galih Prasetyo',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Sudah',
                    'alamat' => 'Jl. Mangga Dua No. 15, Jakarta Barat',
                    'email' => 'galih.prasetyo@gmail.com',
                    'password' => 'galih123',
                    'umur' => 45,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 8,
                    'nama' => 'Dr. Anisa Salsabila',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Belum',
                    'alamat' => 'Jl. Raden Saleh No. 22, Semarang',
                    'email' => 'anisa.salsabila@gmail.com',
                    'password' => 'anisa123',
                    'umur' => 32,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 8,
                    'nama' => 'Dr. Rizky Wardhana',
                    'latar_belakang' => 'Rendah',
                    'status_pernikahan' => 'Cerai',
                    'alamat' => 'Jl. Sudirman No. 18, Palembang',
                    'email' => 'rizky.wardhana@gmail.com',
                    'password' => 'rizky123',
                    'umur' => 39,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],                
                //9
                [
                    'id_spesialis' => 9,
                    'nama' => 'Dr. Anindya Salsabila',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Sudah',
                    'alamat' => 'Jl. Pahlawan No. 12, Malang',
                    'email' => 'anindya.salsabila@gmail.com',
                    'password' => 'anindya123',
                    'umur' => 36,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 9,
                    'nama' => 'Dr. Wirawan Nugroho',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Belum',
                    'alamat' => 'Jl. Kartini No. 45, Semarang',
                    'email' => 'wirawan.nugroho@gmail.com',
                    'password' => 'wirawan123',
                    'umur' => 42,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 9,
                    'nama' => 'Dr. Safira Amelia',
                    'latar_belakang' => 'Rendah',
                    'status_pernikahan' => 'Cerai',
                    'alamat' => 'Jl. Kemuning No. 8, Denpasar',
                    'email' => 'safira.amelia@gmail.com',
                    'password' => 'safira123',
                    'umur' => 39,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                //10
                [
                    'id_spesialis' => 10,
                    'nama' => 'Drg. Anita Prasetyo',
                    'latar_belakang' => 'Menengah',
                    'status_pernikahan' => 'Belum',
                    'alamat' => 'Jl. Cempaka No. 12, Jakarta Timur',
                    'email' => 'anita.prasetyo@gmail.com',
                    'password' => 'anita123',
                    'umur' => 34,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 10,
                    'nama' => 'Drg. Rizky Ramdani',
                    'latar_belakang' => 'Atas',
                    'status_pernikahan' => 'Sudah',
                    'alamat' => 'Jl. Sakura No. 7, Malang',
                    'email' => 'rizky.ramdani@gmail.com',
                    'password' => 'rizky123',
                    'umur' => 40,
                    'jenis_kelamin' => 'Laki-laki',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id_spesialis' => 10,
                    'nama' => 'Drg. Sinta Kusumaningrum',
                    'latar_belakang' => 'Rendah',
                    'status_pernikahan' => 'Cerai',
                    'alamat' => 'Jl. Flamboyan No. 15, Semarang',
                    'email' => 'sinta.kusumaningrum@gmail.com',
                    'password' => 'sinta123',
                    'umur' => 38,
                    'jenis_kelamin' => 'Perempuan',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                
        ]);
    }
}
